export const BUSINESS = {
  name: "Crystal Spring Water Co",
  owner: "Bryan Thompson",
  tagline: "Whole-home water filtration for Florida families",
  phone: "(407) 555-0199",
  phoneTel: "tel:+14075550199",
  email: "hello@crystalspringwaterco.com",
  city: "Orlando",
  region: "FL",
  serviceArea: "Central Florida",
  warrantyYears: 10,
  reviewCount: 342,
  rating: 4.9,
  licenseNumber: "CFC1429876",
  address: "Orlando, FL",
  hours: "Mon–Fri 7am–7pm · Sat 8am–4pm",
  cities: [
    "Orlando",
    "Winter Park",
    "Maitland",
    "Apopka",
    "Sanford",
    "Lake Mary",
    "Altamonte Springs",
    "Casselberry",
    "Kissimmee",
    "St. Cloud",
    "Clermont",
    "Ocoee",
    "Windermere",
  ],
};
